In [26]:
import pandas as pd
import numpy as np

In [42]:
data=pd.read_csv(r"https://raw.githubusercontent.com/plotly/datasets/master/timeseries.csv")

In [28]:
data.head()

Date      A       B       C      D      E      F      G
0  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
1  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
3  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
4  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [29]:
data.columns

Index(['Date', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')

In [30]:
data.index

RangeIndex(start=0, stop=11, step=1)

In [43]:
data.index=data.Date

In [32]:
data.head()

Date      A       B       C      D      E      F      G
Date                                                                     
2008-03-18  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
2008-03-19  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2008-03-20  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
2008-03-25  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
2008-03-26  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [44]:
data.pop('Date')
data.head()

A       B       C      D      E      F      G
Date                                                         
2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

# preprocessing

In [34]:
data.describe()

A           B           C          D          E          F  \
count  11.000000   11.000000   11.000000  11.000000  11.000000  11.000000   
mean   24.227273  163.888182  115.155455  27.061818  19.665455  28.410000   
std     0.239879    0.647438    0.352686   0.795510   0.487737   0.759697   
min    23.810000  163.220000  114.730000  25.780000  19.010000  27.040000   
25%    24.085000  163.395000  114.845000  26.505000  19.370000  27.930000   
50%    24.190000  163.590000  115.110000  27.090000  19.610000  28.250000   
75%    24.360000  164.325000  115.470000  27.615000  19.965000  29.020000   
max    24.680000  164.930000  115.720000  28.220000  20.420000  29.510000   

               G  
count  11.000000  
mean   59.119091  
std     1.964568  
min    56.180000  
25%    58.070000  
50%    59.410000  
75%    59.800000  
max    63.440000

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 2008-03-18 to 2008-04-03
Data columns (total 7 columns):
A    11 non-null float64
B    11 non-null float64
C    11 non-null float64
D    11 non-null float64
E    11 non-null float64
F    11 non-null float64
G    11 non-null float64
dtypes: float64(7)
memory usage: 704.0+ bytes


In [45]:
y=data['G']

In [46]:
y

Date
2008-03-18    63.44
2008-03-19    59.98
2008-03-20    59.61
2008-03-25    59.41
2008-03-26    60.09
2008-03-27    59.62
2008-03-28    58.65
2008-03-31    59.20
2008-04-01    56.18
2008-04-02    56.64
2008-04-03    57.49
Name: G, dtype: float64

In [47]:
data=data.drop(['G'],axis=1)
data.head()

A       B       C      D      E      F
Date                                                  
2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87
2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76
2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04
2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84
2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02

In [48]:
data.values

array([[ 24.68, 164.93, 114.73,  26.27,  19.21,  28.87],
       [ 24.18, 164.89, 114.75,  26.22,  19.07,  27.76],
       [ 23.99, 164.63, 115.04,  25.78,  19.01,  27.04],
       [ 24.14, 163.92, 114.85,  27.41,  19.61,  27.84],
       [ 24.44, 163.45, 114.84,  26.86,  19.53,  28.02],
       [ 24.38, 163.46, 115.4 ,  27.09,  19.72,  28.25],
       [ 24.32, 163.22, 115.56,  27.13,  19.63,  28.24],
       [ 24.19, 164.02, 115.54,  26.74,  19.55,  28.43],
       [ 23.81, 163.59, 115.72,  27.82,  20.21,  29.17],
       [ 24.03, 163.32, 115.11,  28.22,  20.42,  29.38],
       [ 24.34, 163.34, 115.17,  28.14,  20.36,  29.51]])

In [40]:
y.values

array([63.44, 59.98, 59.61, 59.41, 60.09, 59.62, 58.65, 59.2 , 56.18,
       56.64, 57.49])

In [51]:
X=[]
Y_train=[]
values=data.values
for i in range(len(values)):
    X.append([list(values[i])])
    Y_train.append([y[i]])

In [52]:
Y_train

[[63.44],
 [59.98],
 [59.61],
 [59.41],
 [60.09],
 [59.62],
 [58.65],
 [59.2],
 [56.18],
 [56.64],
 [57.49]]

In [53]:
data.values

array([[ 24.68, 164.93, 114.73,  26.27,  19.21,  28.87],
       [ 24.18, 164.89, 114.75,  26.22,  19.07,  27.76],
       [ 23.99, 164.63, 115.04,  25.78,  19.01,  27.04],
       [ 24.14, 163.92, 114.85,  27.41,  19.61,  27.84],
       [ 24.44, 163.45, 114.84,  26.86,  19.53,  28.02],
       [ 24.38, 163.46, 115.4 ,  27.09,  19.72,  28.25],
       [ 24.32, 163.22, 115.56,  27.13,  19.63,  28.24],
       [ 24.19, 164.02, 115.54,  26.74,  19.55,  28.43],
       [ 23.81, 163.59, 115.72,  27.82,  20.21,  29.17],
       [ 24.03, 163.32, 115.11,  28.22,  20.42,  29.38],
       [ 24.34, 163.34, 115.17,  28.14,  20.36,  29.51]])

In [54]:
X

[[[24.68, 164.93, 114.73, 26.27, 19.21, 28.87]],
 [[24.18, 164.89, 114.75, 26.22, 19.07, 27.76]],
 [[23.99, 164.63, 115.04, 25.78, 19.01, 27.04]],
 [[24.14, 163.92, 114.85, 27.41, 19.61, 27.84]],
 [[24.44, 163.45, 114.84, 26.86, 19.53, 28.02]],
 [[24.38, 163.46, 115.4, 27.09, 19.72, 28.25]],
 [[24.32, 163.22, 115.56, 27.13, 19.63, 28.24]],
 [[24.19, 164.02, 115.54, 26.74, 19.55, 28.43]],
 [[23.81, 163.59, 115.72, 27.82, 20.21, 29.17]],
 [[24.03, 163.32, 115.11, 28.22, 20.42, 29.38]],
 [[24.34, 163.34, 115.17, 28.14, 20.36, 29.51]]]

In [55]:
data['X']=X

In [64]:
x_train=data['X'].cumsum()

In [66]:
x_train[3]

[[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],
 [24.18, 164.89, 114.75, 26.22, 19.07, 27.76],
 [23.99, 164.63, 115.04, 25.78, 19.01, 27.04],
 [24.14, 163.92, 114.85, 27.41, 19.61, 27.84]]

In [75]:
import keras


In [83]:
from keras.preprocessing.sequence import pad_sequences
x_train_new=pad_sequences(x,len(data))

In [84]:

x_train_new.shape


(11, 11, 6)

In [86]:
Y_train=np.array(Y_train)
Y_train

array([[63.44],
       [59.98],
       [59.61],
       [59.41],
       [60.09],
       [59.62],
       [58.65],
       [59.2 ],
       [56.18],
       [56.64],
       [57.49]])

In [87]:
from keras.models import Sequential
from keras.layers import Dense,LSTM

# Input layer

In [88]:
s=x_train_new.shape
model=Sequential()
model.add(LSTM(10,input_dim=s[2],input_length=s[1]))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(10, input_shape=(11, 6))`
  This is separate from the ipykernel package so we can avoid doing imports until


Instructions for updating:
Colocations handled automatically by placer.


In [89]:
s

(11, 11, 6)

# Hidden layer

In [90]:
model.add(Dense(10,activation='relu'))

# Output Layer

In [91]:
model.add(Dense(1))

# Compile

In [92]:
model.compile(loss='mean_squared_error',optimizer='sgd')

In [93]:
history=model.fit(x_train_new,Y_train,batch_size=11,epochs=300,verbose=1)

Instructions for updating:
Use tf.cast instead.
Epoch 1/300
11/11 [==============================] - 2s 226ms/step - loss: 3524.2178
Epoch 2/300
11/11 [==============================] - 0s 2ms/step - loss: 1934.1731
Epoch 3/300
11/11 [==============================] - 0s 1ms/step - loss: 5386.9980
Epoch 4/300
11/11 [==============================] - 0s 2ms/step - loss: 3427.6995
Epoch 5/300
11/11 [==============================] - 0s 2ms/step - loss: 3292.1016
Epoch 6/300
11/11 [==============================] - 0s 2ms/step - loss: 3161.8733
Epoch 7/300
11/11 [==============================] - 0s 4ms/step - loss: 3036.8022
Epoch 8/300
11/11 [==============================] - 0s 4ms/step - loss: 2916.6833
Epoch 9/300
11/11 [==============================] - 0s 3ms/step - loss: 2801.3220
Epoch 10/300
11/11 [==============================] - 0s 2ms/step - loss: 2690.5283
Epoch 11/300
11/11 [==============================] - 0s 1ms/step - loss: 2584.1228
Epoch 12/300
11/11 [===============

11/11 [==============================] - 0s 2ms/step - loss: 86.7150
Epoch 97/300
11/11 [==============================] - 0s 816us/step - loss: 83.4201
Epoch 98/300
11/11 [==============================] - 0s 2ms/step - loss: 80.2556
Epoch 99/300
11/11 [==============================] - 0s 725us/step - loss: 77.2164
Epoch 100/300
11/11 [==============================] - 0s 2ms/step - loss: 74.2976
Epoch 101/300
11/11 [==============================] - 0s 907us/step - loss: 71.4943
Epoch 102/300
11/11 [==============================] - 0s 1ms/step - loss: 68.8021
Epoch 103/300
11/11 [==============================] - 0s 2ms/step - loss: 66.2165
Epoch 104/300
11/11 [==============================] - 0s 2ms/step - loss: 63.7333
Epoch 105/300
11/11 [==============================] - 0s 2ms/step - loss: 61.3484
Epoch 106/300
11/11 [==============================] - 0s 2ms/step - loss: 59.0580
Epoch 107/300
11/11 [==============================] - 0s 2ms/step - loss: 56.8582
Epoch 108/300
1

Epoch 195/300
11/11 [==============================] - 0s 1ms/step - loss: 5.0324
Epoch 196/300
11/11 [==============================] - 0s 1ms/step - loss: 4.9721
Epoch 197/300
11/11 [==============================] - 0s 1ms/step - loss: 4.9142
Epoch 198/300
11/11 [==============================] - 0s 906us/step - loss: 4.8585
Epoch 199/300
11/11 [==============================] - 0s 998us/step - loss: 4.8050
Epoch 200/300
11/11 [==============================] - 0s 1ms/step - loss: 4.7537
Epoch 201/300
11/11 [==============================] - 0s 997us/step - loss: 4.7044
Epoch 202/300
11/11 [==============================] - 0s 2ms/step - loss: 4.6571
Epoch 203/300
11/11 [==============================] - 0s 3ms/step - loss: 4.6116
Epoch 204/300
11/11 [==============================] - 0s 1ms/step - loss: 4.5679
Epoch 205/300
11/11 [==============================] - 0s 2ms/step - loss: 4.5260
Epoch 206/300
11/11 [==============================] - 0s 2ms/step - loss: 4.4857
Epoch 207/

Epoch 295/300
11/11 [==============================] - 0s 1ms/step - loss: 3.5355
Epoch 296/300
11/11 [==============================] - 0s 1ms/step - loss: 3.5344
Epoch 297/300
11/11 [==============================] - 0s 1ms/step - loss: 3.5334
Epoch 298/300
11/11 [==============================] - 0s 1ms/step - loss: 3.5324
Epoch 299/300
11/11 [==============================] - 0s 1ms/step - loss: 3.5315
Epoch 300/300
11/11 [==============================] - 0s 2ms/step - loss: 3.5306


In [94]:
model.predict(x_train_new)

array([[58.974075],
       [58.974075],
       [58.974075],
       [58.974075],
       [58.974075],
       [58.974075],
       [58.974075],
       [58.974075],
       [58.974075],
       [58.974075],
       [58.974075]], dtype=float32)

In [95]:
model.save("lstm.h5")

In [96]:
from keras.models import load_model
saved_model=load_model('lstm.h5')